services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://postgres:postgres@voice_learn_postgres/postgres
    ports:
      - 5000:5000
    restart: always

  postgres:
    image: postgres:latest
    container_name: voice_learn_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

networks:
  config-manager_proxy:
    external: true