@url = http://localhost:3000

###
POST {{url}}/auth/login
Content-Type: application/json

{
    "username":"phantomknight287",
    "password":"password"
}


###
POST {{url}}/auth/sign-up
Content-Type: application/json

{
    "username":"phantomknight287",
    "password":"password",
    "name":"Gurpal Singh"
}

###
GET {{url}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InVzZXJfZHpveno4M3Uyb3pvZGhpaHF3bzVuazduIiwiaWF0IjoxNzE1MjM5MzYwfQ.mbrb71K8ltLK3nZKh6ZuF2wIHwmriw8vkE1sBee_0xM

###
GET {{url}}
Authorization: Bearer incorrect_token