@url = http://localhost:5000/v1

###
POST {{url}}/auth/login
Content-Type: application/json

{
    "username":"phantomknight287",
    "password":"password"
}


###
POST {{url}}/auth/sign-up
Content-Type: application/json

{
    "username":"phantomknight287",
    "password":"password",
    "name":"Gurpal Singh"
}

###
GET {{url}}/auth/hydrate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InVzZXJfZXZsdTM0NHF1cXk4MmI0Z3oxZGVhZmlqIiwiaWF0IjoxNzE2NjE5NDUxfQ.8PSjOlYjrXgCW7kZBpD2wnZmLAIIPMpBeXBxiXgkkdE

###
GET {{url}}
Authorization: Bearer incorrect_token

### 
GET {{url}}/onboarding


### 
GET {{url}}/onboarding
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InVzZXJfeGdjNWFvYWx2ajVub2RiZDQwb2d6aXJjIiwiaWF0IjoxNzE3MTQyODc1fQ.UA8aGsG7EdI3T_yZrIl1mbsYKzLxkjzOcWlTNXPMsp4
Content-Type: application/json

{"reason":"For my education","languageId":"language_pv26fpj5y6n2yn3swsrlpupt","knowledge":"I know some words and phrases","analytics":"VoiceLearn.tech"}


###
GET {{url}}/questions/lesson_usjunjz9bi0q4fbf79dkz6x0
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InVzZXJfeGdjNWFvYWx2ajVub2RiZDQwb2d6aXJjIiwiaWF0IjoxNzE3MTQyODc1fQ.UA8aGsG7EdI3T_yZrIl1mbsYKzLxkjzOcWlTNXPMsp4


###
GET {{url}}/lessons/question_h3zw093rxvt95aq0qdjt5mzx/stats
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InVzZXJfeGdjNWFvYWx2ajVub2RiZDQwb2d6aXJjIiwiaWF0IjoxNzE3MTQyODc1fQ.UA8aGsG7EdI3T_yZrIl1mbsYKzLxkjzOcWlTNXPMsp4
