@url = http://localhost:5000/v1
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InVzZXJfdHR3OGU3YzVpZHMwNHJjNnFuNGU3a3BnIiwiaWF0IjoxNzIwNDk5MjY1fQ.wdQzJwh8i5wb4pUuwkJVnQaMKs41ufvM0ZdYdR9HxCY

###
POST {{url}}/auth/sign-in
Content-Type: application/json

{
    "email":"gillgurpal699@gmail.com",
    "password":"password",
    "timezone": "IST",
	"timeZoneOffset": "5:30:00.000000"
}


###
POST {{url}}/auth/sign-up
Content-Type: application/json

{
    "email":"gillgurpal699+2@gmail.com",
    "password":"password",
    "name":"Gurpal Singh"
}

###
GET {{url}}/auth/hydrate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InVzZXJfZXZsdTM0NHF1cXk4MmI0Z3oxZGVhZmlqIiwiaWF0IjoxNzE2NjE5NDUxfQ.8PSjOlYjrXgCW7kZBpD2wnZmLAIIPMpBeXBxiXgkkdE

###
GET {{url}}
Authorization: Bearer incorrect_token

### 
GET {{url}}/onboarding
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InVzZXJfdHR3OGU3YzVpZHMwNHJjNnFuNGU3a3BnIiwiaWF0IjoxNzE4NzM0MzQ2fQ.j_NpJ559JSQc2Ckle3X9KVvnuivff_0L28C3J1ZiNgc

### 
GET {{url}}/onboarding
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InVzZXJfeGdjNWFvYWx2ajVub2RiZDQwb2d6aXJjIiwiaWF0IjoxNzE3MTQyODc1fQ.UA8aGsG7EdI3T_yZrIl1mbsYKzLxkjzOcWlTNXPMsp4
Content-Type: application/json

{"reason":"For my education","languageId":"language_pv26fpj5y6n2yn3swsrlpupt","knowledge":"I know some words and phrases","analytics":"VoiceLearn.tech"}


###
GET {{url}}/questions/lesson_usjunjz9bi0q4fbf79dkz6x0
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InVzZXJfeGdjNWFvYWx2ajVub2RiZDQwb2d6aXJjIiwiaWF0IjoxNzE3MTQyODc1fQ.UA8aGsG7EdI3T_yZrIl1mbsYKzLxkjzOcWlTNXPMsp4


###
GET {{url}}/lessons/question_h3zw093rxvt95aq0qdjt5mzx/stats
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InVzZXJfeGdjNWFvYWx2ajVub2RiZDQwb2d6aXJjIiwiaWF0IjoxNzE3MTQyODc1fQ.UA8aGsG7EdI3T_yZrIl1mbsYKzLxkjzOcWlTNXPMsp4

###
GET {{url}}/streaks/2024/6
Authorization: {{token}}


###
GET {{url}}/profile/@me
Authorization: {{token}}

###
POST {{url}}/auth/forgot-password/email
Content-Type: application/json

{
    "email":"gillgurpal699@gmail.com"
}